global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8000']  # macOS: host.docker.internal routes to host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
